<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nathan Craig">
<meta name="dcterms.date" content="2021-04-28">
<meta name="description" content="An exploration of detention facility contract guaranteed minimums, where are they and what is the expected cost.">

<title>N.Craig - ICE Detention Guaranteed Minimums &amp; Ghost Beds as of April 2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">N.Craig</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="https://n8craig.github.io/inspections/">
 <span class="dropdown-text">ICE Inspections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../posts/2021-06-30-current-ice-detention-population/">
 <span class="dropdown-text">Current ICE Detention</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://n8craig.github.io/nmsu-grades/index.html">
 <span class="dropdown-text">Canvas and R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://nmc.quarto.pub/um-environmental-data/">
 <span class="dropdown-text">Museum Environmental Monitoring</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#sec:facility-types" id="toc-sec:facility-types" class="nav-link" data-scroll-target="#sec\:facility-types">Facility Types</a>
  <ul class="collapse">
  <li><a href="#facility-counts-by-facility-type" id="toc-facility-counts-by-facility-type" class="nav-link" data-scroll-target="#facility-counts-by-facility-type">Facility Counts by Facility Type</a></li>
  <li><a href="#adp-by-facility-type" id="toc-adp-by-facility-type" class="nav-link" data-scroll-target="#adp-by-facility-type">ADP by Facility Type</a></li>
  </ul></li>
  <li><a href="#guaranteed-minimums" id="toc-guaranteed-minimums" class="nav-link" data-scroll-target="#guaranteed-minimums">Guaranteed Minimums</a>
  <ul class="collapse">
  <li><a href="#guaranteed-minimums-by-facility-type" id="toc-guaranteed-minimums-by-facility-type" class="nav-link" data-scroll-target="#guaranteed-minimums-by-facility-type">Guaranteed Minimums by Facility Type</a></li>
  </ul></li>
  <li><a href="#ghost-beds" id="toc-ghost-beds" class="nav-link" data-scroll-target="#ghost-beds">Ghost Beds</a>
  <ul class="collapse">
  <li><a href="#ghost-beds-by-facility-type" id="toc-ghost-beds-by-facility-type" class="nav-link" data-scroll-target="#ghost-beds-by-facility-type">Ghost Beds by Facility Type</a></li>
  <li><a href="#ghost-bed-cost" id="toc-ghost-bed-cost" class="nav-link" data-scroll-target="#ghost-bed-cost">Ghost Bed Cost</a></li>
  </ul></li>
  <li><a href="#supplementary" id="toc-supplementary" class="nav-link" data-scroll-target="#supplementary">Supplementary</a>
  <ul class="collapse">
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information">Session Information</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ICE Detention Guaranteed Minimums &amp; Ghost Beds as of April 2021</h1>
  <div class="quarto-categories">
    <div class="quarto-category">immigration</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>An exploration of detention facility contract guaranteed minimums, where are they and what is the expected cost.</p>
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <a href="https://ncraig.netlify.app/">Nathan Craig</a> 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            NMSU Anthropology, AVID
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 28, 2021</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This post is an exploratory data analysis <span class="citation" data-cites="tukey1977">(<a href="#ref-tukey1977" role="doc-biblioref">Tukey 1977</a>)</span> of ICE detention Guaranteed Minimums based on information reported in ICE’s <a href="https://www.ice.gov/detain/detention-management">FY21 year to date</a> report as of April 15, 2021 <span class="citation" data-cites="ice2021">(<a href="#ref-ice2021" role="doc-biblioref">ICE 2021</a>)</span>. The data on this page are now updated regularly and may be subject to change in the future. This post examines one snapshot in time. Future posts may attempt to further track changes over time.</p>
<p>In addition to looking at Guaranteed Minimums, effort is made here to examine the number of empty Guaranteed Minimum beds which, following Selman and Leighton’s <span class="citation" data-cites="selman2010">(<a href="#ref-selman2010" role="doc-biblioref">2010, 114</a>)</span> term of “ghost inmates” which originates in the private and for-profit corrections incarceration sector, are referred to here as “Ghost Beds.” As Selman and Leighton note because private prisons operate and make money on economies of scale, many for-profit private prison contracts contain clauses that facilities must remain 90% full and if they aren’t the contracts are structured to guaranteed payment for a minimum number of incarcerated persons. ICE facilities, both publicly and privately run, contain Guaranteed Minimums which are listed in the <a href="https://www.ice.gov/detain/detention-management">FY21 year to date</a> report.</p>
<p>ICE’s FY21 year to date report lists each facility’s type, Average Daily Population (ADP) and contractual Guaranteed Minimums. Based on ADP and Guaranteed Minimums, it is possible to estimate the number of empty guaranteed beds or Ghost Beds. It is also possible to explore patterns of ADP, Guaranteed Minimums, and Ghost Beds by facility type.</p>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>For those who may not wish to read through the entire data exploration. A brief summary of some key findings are reported below.</p>
<p>Section 2 data exploration begins by looking at facility types, which appears in ICE’s data set as Type Detailed, as well as ADP by Type Detailed. Private facilities are the most common facility type, though arrangements with US Marshals Service (USMS) are also extremely common. It bears mention that USMS contracts with ICE are under studied and extremely problematic <span class="citation" data-cites="jameson2020">(<a href="#ref-jameson2020" role="doc-biblioref">Jameson 2020</a>)</span>. Not technically private contracts, they operate on a distinct business model related to procurement. While Service Processing Centers (SPC) have the highest ADP by type, Inter-Governmental Service Agreements (IGSA) and Contract Detention Facilities (CDF) are more numerous.</p>
<p>Section 3 looks at Guaranteed Minimums generally and by Type Detailed. At present, there are 34390 guaranteed beds distributed among 50 facilities. There is a strong correlation between total ADP, termed Total Detained and Guaranteed Minimum, Total Detained population explains 46% of the variation in Guaranteed Minimums. As a type, IGSA’s have the largest share of Guaranteed Minimums overall, which is just under 2/3. On average, among facilities with Guaranteed Minimums, IGSA’s tend to have larger Guaranteed Minimums and IGSA’s are more numerous as a type. However, CDF’s, with just under 1/3, also have a large portion of Guaranteed Minimums. IGSA’s and CDF’s make up 90% of the facilities with Guaranteed Minimums and 92% of the Guaranteed Minimum beds.</p>
<p>Section 4 looks at Ghost Beds generally, by Type Detailed and explores Guaranteed Minimum as well as Ghost Bed costs. The mean Guaranteed Minimum per diem is $123.04 (SD=43.02). The total estimated cost of Guaranteed Minimums is $4,308,391 per day, $129,251,730 per month, or $1,572,562,715 per year. At present 2/3 of Guaranteed Minimums are empty Ghost Beds. At the present rate of Ghost Beds, which may change, the total estimated cost is $2,952,525 per day, $88,575,750 per month, or $1,077,671,625 per year.</p>
</section>
</section>
<section id="sec:facility-types" class="level1 page-columns page-full">
<h1>Facility Types</h1>
<p>The <a href="https://www.ice.gov/detain/detention-management">FY21 year to date</a> report lists 142 facilities, five of which are not located on the continental US (<a href="#fig-map-all-facilities">Figure&nbsp;1</a>). ICE lists six kinds of facilities:</p>
<ul>
<li>Bureau of Prisons (BOP) are public facilities.</li>
<li>Contract Detention Facilities (CDF), these are private facilities generally owned by a private prison company.</li>
<li>Intergovernmental Service Agreement (IGSA), these are privately managed facilities owned by a county or municipality whose management is subcontracted to a private prison company.</li>
<li>Service Processing Centers (SPC), are public facilities managed by ICE though often the security staff are subcontracted to a private company.</li>
<li>US Marshals Service Intergovernmental Agreement (USMS IGA) are established US Marshals contracts with local jails that are used by ICE for immigration detention purposes. USMS IGA’s may be a mix of public and private facilities depending on whether local governments subcontract out jail management to a private contractor.</li>
<li>Other</li>
</ul>
<aside>
<p>The five ICE detention facilities located outside of the continental US are:</p>
<ul>
<li>Honolulu Federal Detention Center, HI</li>
<li>Hiland Mountain Correctional Center, AK</li>
<li>Guaynabo MDC PR</li>
<li>Department Of Corrections GU</li>
<li>Saipan Department Of Corrections MP</li>
</ul>
</aside>
<section id="facility-counts-by-facility-type" class="level2">
<h2 class="anchored" data-anchor-id="facility-counts-by-facility-type">Facility Counts by Facility Type</h2>
<p><a href="#tbl-facility-types">Table&nbsp;1</a> and <a href="#fig-facility-types-bar-plot">Figure&nbsp;2</a> show that by count the most common type of facility are IGSA’s (n=73) followed by USMS IGAs (n=39), and CDF (n=17). IGSA’s andCDF’s are private and USMS IGA’s may be a mix of public and private local jails (see list above). Regardless, between IGSA’s and CDF’s 63% (n=90) of ICE detention facilities by count are unambiguously privately managed. USMS IGA’s still operate more as “procurement not policy” in what is an “opaque and intricate business practice” <span class="citation" data-cites="jameson2020">(<a href="#ref-jameson2020" role="doc-biblioref">Jameson 2020</a>: 283)</span> in which local counties and municipalities view detention as a key source of income <span class="citation" data-cites="jameson2020">(<a href="#ref-jameson2020" role="doc-biblioref">Jameson 2020</a>: 2839)</span>.</p>
<div class="cell-output-display">
<div id="fig-map-all-facilities" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-map-all-facilities-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Map of ICE detention facilities.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-facility-types" class="anchored">

<table><caption>Table&nbsp;1:  Count and Percent Total Facilities by Type. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Type Detailed </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> % Total Facilities </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BOP </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 3.52 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 4.23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 11.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> USMS IGA </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 27.46 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 51.41 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output-display">
<div id="fig-facility-types-bar-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-facility-types-bar-plot-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Bar chart of ICE detention facilities by facility type.</figcaption><p></p>
</figure>
</div>
</div>
<p><a href="#fig-facility-map-facet-by-type">Figure&nbsp;3</a> shows were ICE detention facilities are located based on facility type. IGSA’s and USMS IGA’s are more spread out while CDF’s, SPC’s, and Others are primarily located along the southern border.</p>
<div class="cell-output-display">
<div id="fig-facility-map-facet-by-type" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-facility-map-facet-by-type-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Facet map of ICE detention facilities by facility type.</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="adp-by-facility-type" class="level2">
<h2 class="anchored" data-anchor-id="adp-by-facility-type">ADP by Facility Type</h2>
<p>Based on ICE’s FY2021 year to date data table, the total ADP is presently 15,535, which is generally consistent with the detained population reported on the ICE <a href="https://www.ice.gov/coronavirus">Guidance on COVID-19</a> page for this time period. Examining total ADP by facility type shows that IGSA’s (n=8999) and CDF’s (n=3567), which are both private kinds of facilities, make up 81% (n=12566) of the total ADP (see <a href="#tbl-adp-by-facility-type-table">Table&nbsp;2</a>. However, IGSA’s (n=73) and CDF’s (n=17) make up 63% of the total number of facilities. They hold a larger portion of the total ADP because these kinds of facilities are generally larger, though at present SPC’s appear to have a higher mean ADP though there are few of this kind of facility (n=5).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-adp-by-facility-type-table" class="anchored">

<table><caption>Table&nbsp;2:  Summary statistics of ADP by ICE detention facility type. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Type Detailed </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> % Total Facilities </th>
   <th style="text-align:right;"> Total ADP </th>
   <th style="text-align:right;"> Mean ADP </th>
   <th style="text-align:right;"> SD ADP </th>
   <th style="text-align:right;"> % Total ADP </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BOP </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1.41 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 10.00 </td>
   <td style="text-align:right;"> 9.90 </td>
   <td style="text-align:right;"> 0.13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 11.97 </td>
   <td style="text-align:right;"> 3567 </td>
   <td style="text-align:right;"> 209.82 </td>
   <td style="text-align:right;"> 188.57 </td>
   <td style="text-align:right;"> 22.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 51.41 </td>
   <td style="text-align:right;"> 8999 </td>
   <td style="text-align:right;"> 123.27 </td>
   <td style="text-align:right;"> 139.88 </td>
   <td style="text-align:right;"> 57.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 4.23 </td>
   <td style="text-align:right;"> 177 </td>
   <td style="text-align:right;"> 29.50 </td>
   <td style="text-align:right;"> 48.88 </td>
   <td style="text-align:right;"> 1.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 3.52 </td>
   <td style="text-align:right;"> 1349 </td>
   <td style="text-align:right;"> 269.80 </td>
   <td style="text-align:right;"> 121.26 </td>
   <td style="text-align:right;"> 8.68 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> USMS IGA </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 27.46 </td>
   <td style="text-align:right;"> 1423 </td>
   <td style="text-align:right;"> 36.49 </td>
   <td style="text-align:right;"> 45.43 </td>
   <td style="text-align:right;"> 9.16 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Looking at the distribution of ADP by ICE detention facility type, one can see that SPC’s have the highest mean ADP (M=269.80, SD=121.26), while CDF’s (M=209.82, SD=188.57) and IGSA’s (M=123.27, SD=139.88) have the next highest mean ADP (see Table <a href="#tbl-adp-by-facility-type-table">Table&nbsp;2</a>. A combined violin-sina plot <a href="#fig-adp-by-facility-type-figure">Figure&nbsp;4</a> illustrates the distribution of ADP by ICE detention facility type <span class="citation" data-cites="hintze1998 sidiropoulos2018">(<a href="#ref-hintze1998" role="doc-biblioref">Hintze and Nelson 1998</a>; <a href="#ref-sidiropoulos2018" role="doc-biblioref">Sidiropoulos et al. 2018</a>)</span>. So while SPC’s presently have larger detained populations on average, IGSA’s and CDF’s are far more numerous. While USMS IGA’s (n= 39) are the second most numerous kind of facility they have a comparatively lower total ADP (n=1423) or by facility average ADP (M=36.49, SD=45.43).</p>
<div class="cell-output-display">
<div id="fig-adp-by-facility-type-figure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-adp-by-facility-type-figure-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Violin and Sina plot of ADPs by ICE detention facility type.</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="guaranteed-minimums" class="level1">
<h1>Guaranteed Minimums</h1>
<p>Of the 142 facilities reported by ICE in the FY21 year to date dataset, 35% (n=50) have contractual guaranteed minimums (<a href="#tbl-guaranteed-min-by-facility">Table&nbsp;3</a>). The Pearson’s product-moment correlation between Guaranteed Minimum and Total Detained is positive, statistically significant, and very large (<span class="math inline">\(r = 0.68, t(48) = 6.40, p &lt; .001\)</span>). A linear model (estimated using OLS) was applied to predict Guaranteed Minimum with Total Detained. The model explains a statistically significant and substantial proportion of variance (<span class="math inline">\(R^2 = 0.46, F(1, 48) = 40.91, p &lt; .001, adj. R^2 = 0.45\)</span>). The effect of Total Detained on Guaranteed Minimums is statistically significant and positive (<span class="math inline">\(b=2.07, t(48) = 6.40, p &lt; .001\)</span>). Larger facilities have more guaranteed minimums.</p>
<section id="guaranteed-minimums-by-facility-type" class="level2">
<h2 class="anchored" data-anchor-id="guaranteed-minimums-by-facility-type">Guaranteed Minimums by Facility Type</h2>
<p>Facilities with guaranteed minimums are of three types: IGSA’s, CDF’s, and SPC’s (<a href="#fig-histogram-guaranteed-min-by-type">Figure&nbsp;5</a> and <a href="#tbl-guaranteed-min-by-facility-type">Table&nbsp;4</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-guaranteed-min-by-facility" class="anchored">

<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; "><table><caption>Table&nbsp;3:  Guaranteed minimum and total detained by facility. </caption>
 <thead>
  <tr>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Facility </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Type Detailed </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> Guaranteed
Minimum </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> Total Detained </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> SOUTH TEXAS FAMILY RESIDENTIAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 2400 </td>
   <td style="text-align:right;"> 299 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LA PALMA CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1800 </td>
   <td style="text-align:right;"> 428 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LA PALMA CORRECTION CENTER - APSO </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1800 </td>
   <td style="text-align:right;"> 378 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> STEWART DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1600 </td>
   <td style="text-align:right;"> 673 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ADELANTO ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 1455 </td>
   <td style="text-align:right;"> 336 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SOUTH TEXAS ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 1350 </td>
   <td style="text-align:right;"> 734 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TACOMA ICE PROCESSING CENTER (NORTHWEST DET CTR) </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 1181 </td>
   <td style="text-align:right;"> 311 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LASALLE ICE PROCESSING CENTER (JENA) </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1170 </td>
   <td style="text-align:right;"> 464 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OTAY MESA DETENTION CENTER (SAN DIEGO CDF) </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 1100 </td>
   <td style="text-align:right;"> 352 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ADAMS COUNTY DET CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1100 </td>
   <td style="text-align:right;"> 348 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> WINN CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 946 </td>
   <td style="text-align:right;"> 365 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> KARNES COUNTY RESIDENTIAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 830 </td>
   <td style="text-align:right;"> 112 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> PORT ISABEL </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 800 </td>
   <td style="text-align:right;"> 392 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> JACKSON PARISH CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 751 </td>
   <td style="text-align:right;"> 184 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BLUEBONNET DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 374 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MONTGOMERY ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 329 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EL VALLE DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 327 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HOUSTON CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 190 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TORRANCE COUNTY DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 714 </td>
   <td style="text-align:right;"> 24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BROWARD TRANSITIONAL CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 700 </td>
   <td style="text-align:right;"> 331 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SOUTH LOUISIANA DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 700 </td>
   <td style="text-align:right;"> 84 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RICHWOOD CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 677 </td>
   <td style="text-align:right;"> 156 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IMPERIAL REGIONAL DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 640 </td>
   <td style="text-align:right;"> 314 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EL PASO SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 600 </td>
   <td style="text-align:right;"> 323 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IRWIN COUNTY DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 600 </td>
   <td style="text-align:right;"> 314 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> GOLDEN STATE ANNEX </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 560 </td>
   <td style="text-align:right;"> 83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> PRAIRIELAND DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 550 </td>
   <td style="text-align:right;"> 292 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> FOLKSTON MAIN IPC </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 544 </td>
   <td style="text-align:right;"> 123 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DENVER CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 525 </td>
   <td style="text-align:right;"> 218 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> YORK COUNTY PRISON </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 327 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OTERO COUNTY PROCESSING CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 188 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IMMIGRATION CENTERS OF AMERICA FARMVILLE </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 101 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T. DON HUTTO DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 461 </td>
   <td style="text-align:right;"> 71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> KROME NORTH SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 450 </td>
   <td style="text-align:right;"> 310 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DENVER CONTRACT DETENTION FACILITY (CDF) II </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 432 </td>
   <td style="text-align:right;"> 38 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BUFFALO (BATAVIA) SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 400 </td>
   <td style="text-align:right;"> 252 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> FLORENCE SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 392 </td>
   <td style="text-align:right;"> 72 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RIVER CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 361 </td>
   <td style="text-align:right;"> 140 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IAH SECURE ADULT DETENTION FACILITY (POLK) </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 350 </td>
   <td style="text-align:right;"> 76 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MESA VERDE ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 320 </td>
   <td style="text-align:right;"> 43 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> GLADES COUNTY DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 257 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELIZABETH CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 285 </td>
   <td style="text-align:right;"> 102 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RIO GRANDE DETENTION CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 275 </td>
   <td style="text-align:right;"> 155 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CAROLINE DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 224 </td>
   <td style="text-align:right;"> 176 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> YUBA COUNTY JAIL </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 150 </td>
   <td style="text-align:right;"> 19 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DESERT VIEW </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ALLEN PARISH PUBLIC SAFETY COMPLEX </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SAN LUIS REGIONAL DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CALHOUN COUNTY CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 75 </td>
   <td style="text-align:right;"> 114 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> NORTHWESTERN REGIONAL JUVENILE DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table></div>

</div>
</div>
</div>
<div class="cell-output-display">
<div id="fig-histogram-guaranteed-min-by-type" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-histogram-guaranteed-min-by-type-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Histogram of guaranteed minimums by ICE detention facility type.</figcaption><p></p>
</figure>
</div>
</div>
<p>All 5 SPC’s have guaranteed minimums, making up 10% of the facilities with guaranteed minimums, and forming 7.68% of all guaranteed minimum beds. SPC’s average 528 guaranteed beds per facility which is the lowest of the three types. So SPC’s have guaranteed minimums at the highest rate, but they make up a relatively small proportion of the facilities with guaranteed minimums, and a small proportion of the total number of guaranteed beds.</p>
<p>There are 30 IGSA’s that have guaranteed minimums, 41% of this facility type has guaranteed minimums, they constitute 60% of the facilities with guaranteed minimums, which comprises 61.95 of all guaranteed minimum beds. IGSA’s average 710.17 guaranteed beds per facility which is the highest of any of the three types. IGSA’s constitute the majority of facilities with guaranteed minimums and the majority of guaranteed minimum beds. IGSA’s also have the highest per facility guaranteed minimum average. The four facilities with the most number of guaranteed minimum beds are all IGSA’s (<a href="#tbl-guaranteed-min-by-facility">Table&nbsp;3</a>).</p>
<p>There are 15 CFS that have guaranteed minimums, 88% of this type of facility has guaranteed minimums, they make up 10% of all facilities with guaranteed minimums , which comprises 30% of all guaranteed minimum beds, and as a type averages 696.2 guaranteed beds per facility. Thus, a very high proportion of this facility type has guaranteed minimums, but they make up a relatively small proportion of the total number of facilities with guaranteed minimums. CFS’s have average guaranteed minimums that are relatively close to IGSA’s.</p>
<p>Together, CDF’s and IGSA’s constitute 90% of the facilities with guaranteed minimums and 92% of the guaranteed minimum beds (<a href="#fig-guaranteed-min-by-facility-type-figure">Figure&nbsp;6</a>). The overwhelming number of guaranteed minimums are thus in private facilities.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-guaranteed-min-by-facility-type" class="anchored">

<table><caption>Table&nbsp;4:  Guaranteed minimums by facility type. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Type Detailed </th>
   <th style="text-align:right;"> n
Facilities w. Guaranteed
Minimum </th>
   <th style="text-align:right;"> % Facilities by Type w. Guaranteed Minimum </th>
   <th style="text-align:right;"> % Facilities w. Guaranteed Minimum </th>
   <th style="text-align:right;"> Total Guaranteed Minimum </th>
   <th style="text-align:right;"> % Total Guaranteed Minimum </th>
   <th style="text-align:right;"> Mean Guaranteed Minimum </th>
   <th style="text-align:right;"> SD Guaranteed Minimum </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 10443 </td>
   <td style="text-align:right;"> 30.37 </td>
   <td style="text-align:right;"> 696.20 </td>
   <td style="text-align:right;"> 409.53 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 41 </td>
   <td style="text-align:right;"> 60 </td>
   <td style="text-align:right;"> 21305 </td>
   <td style="text-align:right;"> 61.95 </td>
   <td style="text-align:right;"> 710.17 </td>
   <td style="text-align:right;"> 567.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 2642 </td>
   <td style="text-align:right;"> 7.68 </td>
   <td style="text-align:right;"> 528.40 </td>
   <td style="text-align:right;"> 173.30 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell-output-display">
<div id="fig-guaranteed-min-by-facility-type-figure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-guaranteed-min-by-facility-type-figure-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Violin and Sina plot of guaranteed minimum by ICE detention facility type.</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="ghost-beds" class="level1">
<h1>Ghost Beds</h1>
<p>Of the 50 facilities that have guaranteed minimums, all but one report a facility Total ADP that is lower than the facility guaranteed minimum (<a href="#tbl-ghost-bed-by-facility">Table&nbsp;5</a>). Only the Calhoun County Correctional Center has a total ADP that is higher than the facility guaranteed minimum number of beds. Unoccupied guaranteed minimum beds are termed “ghost beds.” There are a total of 22960 ghost beds that are located in CDF’s, IGSA’s, and SPC’s. Given this, during FY21 up to April, 67% of Guaranteed Minimum beds are Ghost Beds that are being paid for and are empty.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ghost-bed-by-facility" class="anchored">

<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; "><table><caption>Table&nbsp;5:  Estimated number of ghost beds by ICE detention facility. </caption>
 <thead>
  <tr>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Facility </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Type Detailed </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> Estimated Ghost Beds </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> Guaranteed Minimums </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> Total Detained </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> SOUTH TEXAS FAMILY RESIDENTIAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 2101 </td>
   <td style="text-align:right;"> 2400 </td>
   <td style="text-align:right;"> 299 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LA PALMA CORRECTION CENTER - APSO </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1422 </td>
   <td style="text-align:right;"> 1800 </td>
   <td style="text-align:right;"> 378 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LA PALMA CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 1372 </td>
   <td style="text-align:right;"> 1800 </td>
   <td style="text-align:right;"> 428 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ADELANTO ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 1119 </td>
   <td style="text-align:right;"> 1455 </td>
   <td style="text-align:right;"> 336 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> STEWART DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 927 </td>
   <td style="text-align:right;"> 1600 </td>
   <td style="text-align:right;"> 673 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TACOMA ICE PROCESSING CENTER (NORTHWEST DET CTR) </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 870 </td>
   <td style="text-align:right;"> 1181 </td>
   <td style="text-align:right;"> 311 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ADAMS COUNTY DET CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 752 </td>
   <td style="text-align:right;"> 1100 </td>
   <td style="text-align:right;"> 348 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OTAY MESA DETENTION CENTER (SAN DIEGO CDF) </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 748 </td>
   <td style="text-align:right;"> 1100 </td>
   <td style="text-align:right;"> 352 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> KARNES COUNTY RESIDENTIAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 718 </td>
   <td style="text-align:right;"> 830 </td>
   <td style="text-align:right;"> 112 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> LASALLE ICE PROCESSING CENTER (JENA) </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 706 </td>
   <td style="text-align:right;"> 1170 </td>
   <td style="text-align:right;"> 464 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TORRANCE COUNTY DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 690 </td>
   <td style="text-align:right;"> 714 </td>
   <td style="text-align:right;"> 24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SOUTH TEXAS ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 616 </td>
   <td style="text-align:right;"> 1350 </td>
   <td style="text-align:right;"> 734 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SOUTH LOUISIANA DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 616 </td>
   <td style="text-align:right;"> 700 </td>
   <td style="text-align:right;"> 84 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> WINN CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 581 </td>
   <td style="text-align:right;"> 946 </td>
   <td style="text-align:right;"> 365 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> JACKSON PARISH CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 567 </td>
   <td style="text-align:right;"> 751 </td>
   <td style="text-align:right;"> 184 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> HOUSTON CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 560 </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 190 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RICHWOOD CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 521 </td>
   <td style="text-align:right;"> 677 </td>
   <td style="text-align:right;"> 156 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> GOLDEN STATE ANNEX </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 477 </td>
   <td style="text-align:right;"> 560 </td>
   <td style="text-align:right;"> 83 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EL VALLE DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 423 </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 327 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MONTGOMERY ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 421 </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 329 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> FOLKSTON MAIN IPC </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 421 </td>
   <td style="text-align:right;"> 544 </td>
   <td style="text-align:right;"> 123 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> PORT ISABEL </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 408 </td>
   <td style="text-align:right;"> 800 </td>
   <td style="text-align:right;"> 392 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IMMIGRATION CENTERS OF AMERICA FARMVILLE </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 399 </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 101 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DENVER CONTRACT DETENTION FACILITY (CDF) II </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 394 </td>
   <td style="text-align:right;"> 432 </td>
   <td style="text-align:right;"> 38 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> T. DON HUTTO DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 390 </td>
   <td style="text-align:right;"> 461 </td>
   <td style="text-align:right;"> 71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BLUEBONNET DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 376 </td>
   <td style="text-align:right;"> 750 </td>
   <td style="text-align:right;"> 374 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BROWARD TRANSITIONAL CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 369 </td>
   <td style="text-align:right;"> 700 </td>
   <td style="text-align:right;"> 331 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IMPERIAL REGIONAL DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 326 </td>
   <td style="text-align:right;"> 640 </td>
   <td style="text-align:right;"> 314 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> FLORENCE SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 320 </td>
   <td style="text-align:right;"> 392 </td>
   <td style="text-align:right;"> 72 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OTERO COUNTY PROCESSING CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 312 </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 188 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DENVER CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 307 </td>
   <td style="text-align:right;"> 525 </td>
   <td style="text-align:right;"> 218 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IRWIN COUNTY DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 286 </td>
   <td style="text-align:right;"> 600 </td>
   <td style="text-align:right;"> 314 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EL PASO SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 277 </td>
   <td style="text-align:right;"> 600 </td>
   <td style="text-align:right;"> 323 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MESA VERDE ICE PROCESSING CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 277 </td>
   <td style="text-align:right;"> 320 </td>
   <td style="text-align:right;"> 43 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IAH SECURE ADULT DETENTION FACILITY (POLK) </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 274 </td>
   <td style="text-align:right;"> 350 </td>
   <td style="text-align:right;"> 76 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> PRAIRIELAND DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 258 </td>
   <td style="text-align:right;"> 550 </td>
   <td style="text-align:right;"> 292 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RIVER CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 221 </td>
   <td style="text-align:right;"> 361 </td>
   <td style="text-align:right;"> 140 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELIZABETH CONTRACT DETENTION FACILITY </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 183 </td>
   <td style="text-align:right;"> 285 </td>
   <td style="text-align:right;"> 102 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> YORK COUNTY PRISON </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 173 </td>
   <td style="text-align:right;"> 500 </td>
   <td style="text-align:right;"> 327 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BUFFALO (BATAVIA) SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 148 </td>
   <td style="text-align:right;"> 400 </td>
   <td style="text-align:right;"> 252 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> KROME NORTH SERVICE PROCESSING CENTER </td>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 140 </td>
   <td style="text-align:right;"> 450 </td>
   <td style="text-align:right;"> 310 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> YUBA COUNTY JAIL </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 131 </td>
   <td style="text-align:right;"> 150 </td>
   <td style="text-align:right;"> 19 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RIO GRANDE DETENTION CENTER </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 275 </td>
   <td style="text-align:right;"> 155 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> DESERT VIEW </td>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 107 </td>
   <td style="text-align:right;"> 120 </td>
   <td style="text-align:right;"> 13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CAROLINE DETENTION FACILITY </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 48 </td>
   <td style="text-align:right;"> 224 </td>
   <td style="text-align:right;"> 176 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SAN LUIS REGIONAL DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 46 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> GLADES COUNTY DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 43 </td>
   <td style="text-align:right;"> 300 </td>
   <td style="text-align:right;"> 257 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ALLEN PARISH PUBLIC SAFETY COMPLEX </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 36 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> NORTHWESTERN REGIONAL JUVENILE DETENTION CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CALHOUN COUNTY CORRECTIONAL CENTER </td>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> -39 </td>
   <td style="text-align:right;"> 75 </td>
   <td style="text-align:right;"> 114 </td>
  </tr>
</tbody>
</table></div>

</div>
</div>
</div>
<p>Does Total Detained explain the presence and amount of Ghost Beds? The Pearson’s product-moment correlation between Ghost Beds and Total Detained is positive, statistically significant, and very large (<span class="math inline">\(r = 0.43, t(48) = 3.30, p &lt; .01\)</span>). Using a linear model to predict Ghost Beds by Total Detained (<a href="#fig-scatterplot-ghost-bed-by-total-detained">Figure&nbsp;7</a>) explains a statistically significant and moderate proportion of variance (<span class="math inline">\(R^2 = 0.18, F(1, 48) = 10.88, p = 0.002, adj. R^2 = 0.17\)</span>). The effect of Total Detained on Ghost Beds is statistically significant and positive (<span class="math inline">\(b = 1.07,t(48) = 3.30, p &lt; .01\)</span>). Total Detained explains about 18% of Ghost Beds. This is probably related to the fact that Total Detained predicts the amount of Guaranteed Minimum (Section 3).</p>
<div class="cell-output-display">
<div id="fig-scatterplot-ghost-bed-by-total-detained" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-scatterplot-ghost-bed-by-total-detained-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Scatterplot of Ghost Beds by Total Detained.</figcaption><p></p>
</figure>
</div>
</div>
<p>Does the amount of Guaranteed Minimum explain the presence and amount of Ghost Beds? The Pearson’s product-moment correlation between Ghost Beds and Guaranteed Minimum is positive, statistically significant, and very large (<span class="math inline">\(r = 0.96, t(48) = 22.31, p &lt; .001\)</span>). Using a linear model to predict Ghost Beds by Guaranteed Minimum (<a href="#fig-scatterplot-ghost-beds-by-guaranteed-min">Figure&nbsp;8</a>) explains a statistically significant and very large proportion of the variance (<span class="math inline">\(R^2 = 0.91, F(1, 48) = 497.86, p &lt; .001, adj. R^2 = 0.91\)</span>). The effect of Guaranteed Minimum on Ghost Beds is statistically significant and positive (<span class="math inline">\(b = 0.78, t(48) = 22.31, p &lt; .001\)</span>). The presence of Guaranteed Minimums explains 91% of Ghost Beds.</p>
<div class="cell-output-display">
<div id="fig-scatterplot-ghost-beds-by-guaranteed-min" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-scatterplot-ghost-beds-by-guaranteed-min-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8: Scatterplot of Ghost Beds by Guaranteed Minimum</figcaption><p></p>
</figure>
</div>
</div>
<section id="ghost-beds-by-facility-type" class="level2">
<h2 class="anchored" data-anchor-id="ghost-beds-by-facility-type">Ghost Beds by Facility Type</h2>
<p><a href="#tbl-ghost-bed-by-facility-type">Table&nbsp;6</a> provides some summary figures for ghost beds by facility type. Just as all SPC’s have guaranteed minimums, all SPC’s also have ghost beds, and they make up 10% of the facilities with ghost beds. There are a total of 1293 ghost beds in SPC’s representing 5.63% of the total number of ghost beds. SPC’s average 258.6 ghost beds per facility which is the lowest among the three types of facilities that have ghost beds.</p>
<p>There are 29 IGSA’s that have ghost beds representing 58% of the facilities with Ghost Beds. There are 14,812 Ghost Beds in IGSA facilities making up 64.51% of all ICE Ghost Beds. With an average of 510.76 Ghost Beds per facility, IGSA’s have the highest mean Ghost Beds of any of the three types of facilities.</p>
<p>There are 15 CDF’s that have Ghost Beds representing 30% of the facilities that have Ghost Beds. There are a total of 6,894 Ghost Beds in CDF’s representing 30.03% of all ICE Ghost Beds. Having an average of 459.6 ghost bed per facility, CDF’s fall in between IGSA’s and SPC’s.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ghost-bed-by-facility-type" class="anchored">

<table><caption>Table&nbsp;6:  Ghost beds by facility type. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Type Detailed </th>
   <th style="text-align:right;"> n Facilities w. Ghost Beds </th>
   <th style="text-align:right;"> % Facilities by Type w. Ghost Beds </th>
   <th style="text-align:right;"> % Faciliites w. Ghost Beds </th>
   <th style="text-align:right;"> Total Ghost Beds </th>
   <th style="text-align:right;"> % Total Ghost Beds </th>
   <th style="text-align:right;"> Mean Ghost Beds </th>
   <th style="text-align:right;"> SD Ghost Beds </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> CDF </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 88 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 6894 </td>
   <td style="text-align:right;"> 30.03 </td>
   <td style="text-align:right;"> 459.60 </td>
   <td style="text-align:right;"> 283.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IGSA </td>
   <td style="text-align:right;"> 29 </td>
   <td style="text-align:right;"> 40 </td>
   <td style="text-align:right;"> 58 </td>
   <td style="text-align:right;"> 14812 </td>
   <td style="text-align:right;"> 64.51 </td>
   <td style="text-align:right;"> 510.76 </td>
   <td style="text-align:right;"> 470.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SPC </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1293 </td>
   <td style="text-align:right;"> 5.63 </td>
   <td style="text-align:right;"> 258.60 </td>
   <td style="text-align:right;"> 114.81 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p><a href="#fig-ghost-bed-by-facility-type-figure">Figure&nbsp;9</a> provides a violin-sina plot of Ghost Beds by facility type and shows that IGSA’s have the highest mean number of Ghost Beds and several IGSA facilities have a very large number of Ghost Beds. <a href="#fig-map-ghost-beds">Figure&nbsp;10</a> provides a map of Ghost Beds in the continental US. The map shows that Ghost Beds are concentrated on the southern border.</p>
<div class="cell-output-display">
<div id="fig-ghost-bed-by-facility-type-figure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-ghost-bed-by-facility-type-figure-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;9: Violin-Sina plot of ghost beds by ICE detention facility type.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell" data-preview="true">
<div class="cell-output-display">
<div id="fig-map-ghost-beds" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-map-ghost-beds-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10: Map of estimated number of ghost beds in ICE detention facilities.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ghost-bed-cost" class="level2">
<h2 class="anchored" data-anchor-id="ghost-bed-cost">Ghost Bed Cost</h2>
<p>As of April, the ICE’s FY21 year to date data table lists 51 facilities with Guaranteed Minimums but unfortunately does not supply the per diem rate for any of those contracts. The DHS budget request for FY21 provides information on 27 facilities with guaranteed minimums <span class="citation" data-cites="dhs2020">(<a href="#ref-dhs2020" role="doc-biblioref">DHS 2020</a>, ICE-O&amp;S-137)</span>, and among those facilities (n=27) the mean per diem is $123.04 (SD=43.02). Presumably, the Guaranteed Minimums at the remaining 23 facilities were established after the FY21 budget request. For the purpose of estimating the total cost of Guaranteed Minimums and unused Ghost Beds, for the 23 facilities for which Guaranteed Minimums are unlisted the average of the Guaranteed Minimums per diem rate for the 27 facilities listed in the FY21 budget request are used <span class="citation" data-cites="dhs2020">(<a href="#ref-dhs2020" role="doc-biblioref">DHS 2020</a>, ICE-O&amp;S-137)</span>.</p>
<p>Based on reported Guaranteed Minimum per diem rates, and average rates where not reported, the total daily cost of Guaranteed Minimum ICE detention beds is $4,308,391 and the total estimated cost of Ghost Beds is $2,952,525.</p>
<p><a href="#fig-guaranteed-min-per-diem">Figure&nbsp;11</a> shows the Guaranteed Minimum per diem rate by facility type. SPC’s tend to have higher Guaranteed Minimum per diem costs than either CDF’s or IGSA’s. One reason that a large number of IGSA’s guaranteed minimums hover around a per diem of 125 is that many of these facilities are not listed in the FY21 year to date figures and the values are based on averages. <em>It would be good to determine which kinds of facilities have new Guaranteed Minimums</em>. <a href="#fig-guaranteed-minimum-average-cost-by-facility-type">Figure&nbsp;12</a> shows the average Guaranteed Minimum cost by facility type. On average, most facilities have roughly similar costs even though IGSA’s and CFS’s are larger. The leveling of average cost may be related to the higher per diems for SPC’s. <a href="#fig-ghost-bed-cost-by-facility-type">Figure&nbsp;13</a> shows the average Ghost Bed cost by facility type. SPC’s have slightly lower costs than IGSA’s and CDF’s.</p>
<div class="cell-output-display">
<div id="fig-guaranteed-min-per-diem" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-guaranteed-min-per-diem-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11: Violin-sina plot of Guaranteed Minimum per diem rate by ICE detention Type Detailed.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-guaranteed-minimum-average-cost-by-facility-type" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-guaranteed-minimum-average-cost-by-facility-type-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;12: Violin-sina plot of average Guaranteed Minimum Cost by ICE detention Type Detailed.</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-ghost-bed-cost-by-facility-type" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ice-detention-guaranteed-minimums_files/figure-html/fig-ghost-bed-cost-by-facility-type-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13: Violin-sina plot of Ghost Bed Cost by ICE detention Type Detailed.</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="supplementary" class="level1">
<h1>Supplementary</h1>
<section id="session-information" class="level2">
<h2 class="anchored" data-anchor-id="session-information">Session Information</h2>
<p>Analyses were conducted using the R Statistical language (version 4.2.1; R Core Team, 2022) on Windows 10 x64 (build 19044)</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>The following R packages were used used in preparing this document.</p>
<ul>
<li>rmarkdown (version 2.18; Allaire J et al., 2022)</li>
<li>ggthemes (version 4.2.4; Arnold J, 2021)</li>
<li>effectsize (version 0.8.2; Ben-Shachar MS et al., 2020)</li>
<li>rio (version 0.5.29; Chan C et al., 2021)</li>
<li>summarytools (version 1.0.1; Comtois D, 2022)</li>
<li>janitor (version 2.1.0; Firke S, 2021)</li>
<li>purrr (version 0.3.5; Henry L, Wickham H, 2022)</li>
<li>parameters (version 0.20.0; Lüdecke D et al., 2020)</li>
<li>performance (version 0.10.1; Lüdecke D et al., 2021)</li>
<li>easystats (version 0.6.0; Lüdecke D et al., 2022)</li>
<li>see (version 0.7.4; Lüdecke D et al., 2021)</li>
<li>insight (version 0.18.8; Lüdecke D et al., 2019)</li>
<li>bayestestR (version 0.13.0; Makowski D et al., 2019)</li>
<li>modelbased (version 0.8.5; Makowski D et al., 2020)</li>
<li>correlation (version 0.8.3; Makowski D et al., 2020)</li>
<li>report (version 0.5.5; Makowski D et al., 2021)</li>
<li>tibble (version 3.1.8; Müller K, Wickham H, 2022)</li>
<li>ggstatsplot (version 0.10.0; Patil I, 2021)</li>
<li>datawizard (version 0.6.4; Patil I et al., 2022)</li>
<li>sf (version 1.0.9; Pebesma E, 2018)</li>
<li>ggforce (version 0.4.1; Pedersen T, 2022)</li>
<li>R (version 4.2.1; R Core Team, 2022)</li>
<li>ggplot2 (version 3.4.0; Wickham H, 2016)</li>
<li>forcats (version 0.5.2; Wickham H, 2022)</li>
<li>stringr (version 1.4.1; Wickham H, 2022)</li>
<li>tidyverse (version 1.3.2; Wickham H et al., 2019)</li>
<li>readxl (version 1.4.1; Wickham H, Bryan J, 2022)</li>
<li>dplyr (version 1.0.10; Wickham H et al., 2022)</li>
<li>tidyr (version 1.2.1; Wickham H, Girlich M, 2022)</li>
<li>readr (version 2.1.3; Wickham H et al., 2022)</li>
<li>knitr (version 1.39; Xie Y, 2022)</li>
<li>kableExtra (version 1.3.4; Zhu H, 2021)</li>
</ul>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-dhs2020" class="csl-entry" role="doc-biblioentry">
DHS. 2020. <span>“Department of Homeland Security, u.s. Immigration and Customs Enforcement Budget Overview, Fiscal Year 2021 Congressional Justification,”</span> February. <a href="https://www.dhs.gov/sites/default/files/publications/u.s._immigration_and_customs_enforcement.pdf">https://www.dhs.gov/sites/default/files/publications/u.s._immigration_and_customs_enforcement.pdf</a>.
</div>
<div id="ref-hintze1998" class="csl-entry" role="doc-biblioentry">
Hintze, Jerry L., and Ray D. Nelson. 1998. <span>“Violin Plots: A Box Plot-Density Trace Synergism.”</span> <em>The American Statistician</em> 52 (2): 181–84. <a href="https://doi.org/10.1080/00031305.1998.10480559">https://doi.org/10.1080/00031305.1998.10480559</a>.
</div>
<div id="ref-ice2021" class="csl-entry" role="doc-biblioentry">
ICE. 2021. <span>“Detention Management.”</span> <a href="https://www.ice.gov/detain/detention-management">https://www.ice.gov/detain/detention-management</a>.
</div>
<div id="ref-jameson2020" class="csl-entry" role="doc-biblioentry">
Jameson, Ellyn. 2020. <span>“ICE Detention Through u.s. Marshals Agreements.”</span> <em>Georgetown Immigration Law Journal</em> 35 (1): 279–315. <a href="https://www.law.georgetown.edu/immigration-law-journal/in-print/volume-35-number-1-fall-2020/ice-detention-through-u-s-marshals-agreements/">https://www.law.georgetown.edu/immigration-law-journal/in-print/volume-35-number-1-fall-2020/ice-detention-through-u-s-marshals-agreements/</a>.
</div>
<div id="ref-selman2010" class="csl-entry" role="doc-biblioentry">
Selman, Donna, and Paul Leighton. 2010. <em>Punishment for Sale: Private Prisons, Big Business, and the Incarceration Binge</em>. Issues in Crime &amp; Justice. Lanham, Md: Rowman &amp; Littlefield Publishers.
</div>
<div id="ref-sidiropoulos2018" class="csl-entry" role="doc-biblioentry">
Sidiropoulos, Nikos, Sina Hadi Sohi, Thomas Lin Pedersen, Bo Torben Porse, Ole Winther, Nicolas Rapin, and Frederik Otzen Bagger. 2018. <span>“SinaPlot: An Enhanced Chart for Simple and Truthful Representation of Single Observations over Multiple Classes.”</span> <em>Journal of Computational and Graphical Statistics</em> 27 (3): 673–76. <a href="https://doi.org/10.1080/10618600.2017.1366914">https://doi.org/10.1080/10618600.2017.1366914</a>.
</div>
<div id="ref-tukey1977" class="csl-entry" role="doc-biblioentry">
Tukey, John Wilder. 1977. <em>Exploratory Data Analysis</em>. Addison-Wesley Series in Behavioral Science. Reading, Mass: Addison-Wesley Pub. Co.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>