---
title: "GDELT comparison"
author: "Nathan Craig"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(newsflash)
library(httr)
library(jsonlite)
library(ggplot2)
library(patchwork)
```

```{r read-csv-simple-call, message = FALSE, warning = FALSE, code_folding=FALSE}
# paste in the text from the GUI search box.
# note that entire string should be contained in single quotes
search_term <- '"critical race theory"'

# Paste the request URL into a read_csv call and assign to variable
df <- read_csv("https://api.gdeltproject.org/api/v2/tv/tv?format=csv&timespan=FULL&last24=yes&dateres=DAY&query=%22critical%20race%20theory%22%20(station:BLOOMBERG%20OR%20station:CNBC%20OR%20station:CNN%20OR%20station:CSPAN%20OR%20station:CSPAN2%20OR%20station:CSPAN3%20OR%20station:FBC%20OR%20station:FOXNEWS%20OR%20station:MSNBC%20)%20&mode=timelinevol&timezoom=yes")  %>% 
  rename(date = 1,
         network = 2,
         value = 3) %>% 
  mutate(search = search_term)
df
```

```{r read-csv-simple-plot, fig.cap="Sample output timeline of a simple search retrieved using `read_csv`."}
df %>% 
  ggplot(aes(date, value, color=network))+
  geom_line(alpha = 0.75)+
  labs(title = paste("TV Volume Timeline:", search_term),
     subtitle = "Coverage Volume Normalized Daily Resolution",
     caption = "Data Source: https://api.gdeltproject.org/api/v2/summary/summary",
     color = "Network")+
xlab("Date")+
ylab("% Airtime (15sec Blocks)")
```

## Reading JSON Data

There is a tidyr article on [rectangling](https://tidyr.tidyverse.org/articles/rectangle.html) which is "the art and craft of taking a deeply nested list (often sourced from wild caught JSON or XML) and taming it into a tiday data set of rows and columns." Yes, this is what we want to do. Tom Mok also has a nice [page](https://themockup.blog/posts/2020-05-22-parsing-json-in-r-with-jsonlite/) "Easily pasrin JSON in R with jsonlite and purrr."
