---
title: "ANOVA total_detained~type_detailed"
output: html_notebook
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(ggplot2)
library(ggforce)
library(ggthemes)
library(easystats)
library(rmarkdown)
library(readr)
library(kableExtra)
library(knitr)
# knitr option that forces rounding
opts_chunk$set(results = 'asis',
               comment = NA,
               prompt = FALSE,
               cache = FALSE)
```

```{r include=FALSE}
facilities <- read_csv("https://raw.githubusercontent.com/n8craig/IDE-Detention-Year-End-Reports/main/data/facilities%20geocoded.csv")

facilities$`Type Detailed` <- as.factor(facilities$`Type Detailed`)
# Adding new columns
facilities <- facilities %>% 
  mutate(`Total Detained`=
           `Female Crim` +
           `Female Non-Crim` +
           `Male Crim` +
           `Male Non-Crim`) %>% 
  mutate(`Total Males Detained` =
           `Male Crim` +
           `Male Non-Crim`) %>% 
  mutate(`Total Females Detained` =
           `Female Crim` +
           `Female Non-Crim`) %>% 
  mutate(`Percent No Threat` =
            (`No ICE Threat Level` /
           `Total Detained`)*100) %>% 
  relocate(c(`Total Females Detained`,
             `Total Males Detained`,
             `Total Detained`,
             `Percent No Threat`), .after = `Guaranteed Minimum`) %>% 
  clean_names()
```

```{r}
facilities %>% 
  group_by(., type_detailed) %>% 
  summarise(
    count = n(),
    mean = mean(total_detained, na.rm = TRUE),
    sd = sd(total_detained, na.rm = TRUE),
    sum = sum(total_detained, na.rm = TRUE)
            ) %>% 
  kable() %>% 
  kable_styling(full_width = F, position = "center")
```

```{r}
aov.model <- aov(total_detained~type_detailed, data = facilities)
report(aov.model)
```

```{r total-detained-by-type-tukeyHSD}
# Calculate Tukey's Honest Significant Difference (HSD) testTukey, John (1949). "Comparing Individual Means in the Analysis of Variance". Biometrics. 5 (2): 99–114. JSTOR 3001913
aov.model.turkeyHSD <- TukeyHSD(aov.model, conf.level = 0.95)

aov.model.turkeyHSD$type_detailed %>% 
  kable(
    caption = "Tukey HSD output, significant relationships shown in bold.",
    digits = 2) %>% 
  row_spec(c(7,9,12), bold=T) %>% 
  kable_styling(full_width = F, position = "center")
```

```{r total-detained-by-type-tukeyHSD-plot, fig.cap="Plot of Tukey HSD test of paired relationships in ANOVA of Total Detained by Type Detailed."}
par(mar=c(3,9,3,2))
plot(aov.model.turkeyHSD, las=1)

```

```{r}
report_system()
```

```{r}
report(sessionInfo())
```
