<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nathan Craig">
<meta name="dcterms.date" content="2022-01-19">
<meta name="description" content="This how-to explores some issues with formatting text called by R Markdown’s ability to include inline code. Topics covered include conditional formatting of numbers by means of knitr hooks as well as strategies for reporting really small p values">

<title>nmc - Formatting Inline Code and Reporting \(p\)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<link href="..\..\site_libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">nmc</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="https://n8craig.github.io/inspections/">
 <span class="dropdown-text">ICE Inspections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../posts/2021-06-30-current-ice-detention-population/">
 <span class="dropdown-text">Current ICE Detention</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://n8craig.github.io/nmsu-grades/index.html">
 <span class="dropdown-text">Canvas and R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://nmc.quarto.pub/um-environmental-data/">
 <span class="dropdown-text">Museum Environmental Monitoring</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#conditional-formatting-of-inline-code-using-knitrknit_hooks" id="toc-conditional-formatting-of-inline-code-using-knitrknit_hooks" class="nav-link" data-scroll-target="#conditional-formatting-of-inline-code-using-knitrknit_hooks">Conditional formatting of inline code using <code>knitr::knit_hooks()</code></a></li>
  <li><a href="#exploring-inline-formatting-of-numeric-variables" id="toc-exploring-inline-formatting-of-numeric-variables" class="nav-link" data-scroll-target="#exploring-inline-formatting-of-numeric-variables">Exploring inline formatting of numeric variables</a></li>
  <li><a href="#reporting-statistical-tests-inline" id="toc-reporting-statistical-tests-inline" class="nav-link" data-scroll-target="#reporting-statistical-tests-inline">Reporting statistical tests inline</a></li>
  <li><a href="#reporting-p-values" id="toc-reporting-p-values" class="nav-link" data-scroll-target="#reporting-p-values">Reporting <span class="math inline">\(p\)</span> values</a>
  <ul class="collapse">
  <li><a href="#right-skewed-distribution" id="toc-right-skewed-distribution" class="nav-link" data-scroll-target="#right-skewed-distribution">Right skewed distribution</a></li>
  <li><a href="#a-normal-distribution" id="toc-a-normal-distribution" class="nav-link" data-scroll-target="#a-normal-distribution">A normal distribution</a></li>
  <li><a href="#left-skewed-distribution" id="toc-left-skewed-distribution" class="nav-link" data-scroll-target="#left-skewed-distribution">Left skewed distribution</a></li>
  </ul></li>
  <li><a href="#helpful-links" id="toc-helpful-links" class="nav-link" data-scroll-target="#helpful-links">Helpful Links:</a></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Formatting Inline Code and Reporting <span class="math inline">\(p\)</span></h1>
  <div class="quarto-categories">
    <div class="quarto-category">R Markdown</div>
    <div class="quarto-category">how-to</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>This how-to explores some issues with formatting text called by R Markdown’s ability to include inline code. Topics covered include conditional formatting of numbers by means of <code>knitr</code> hooks as well as strategies for reporting really small <span class="math inline">\(p\)</span> values</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nathan Craig </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1 page-columns page-full">
<h1>Introduction</h1>
<p>One of the advantages of writing in R Markdown is the ability to use inline code, particularly to call up and report a variable produced through analysis. This feature is especially useful when data need to be updated and values in the text change. Rather than re-copying the values in the text when analysis is refined, with inline code the results of the calculations update when the functions are altered or applied to the modified data set. While this is wonderful, it is often necessary to format numbers in particular ways. For example, APA <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">style</a> calls for “commas between groups of three digits” with some exceptions for things like “page numbers, binary digits, serial numbers, degrees of temperature, degrees of freedom, and acoustic frequencies above 1000.”</p>
<div class="cell page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<p><img src="https://i.imgur.com/XZ2xlrq.jpeg" class="img-fluid"></p>
</div></div></div>
<p>Formatting inline numbers in R markdown can seem tricky, perhaps leading one to fall back on repetitive or “hacky” solutions. However, R is an <a href="https://stackoverflow.com/questions/802050/what-is-opinionated-software">opinionated</a> language; so while there is more than one way to format inline numbers, some approaches are better than others. In the past, I often formatted the number inline by wrapping the <code>round()</code> function around whatever value I’m calling. I did this individually on a variable by variable basis which is unnecessarily repetitive and prone to breaking. It also makes for longer inline code which has harder to “read through.” Fortunately, there is a better way!</p>
<p>Recently, from Pat Schloss’s Code Club <a href="https://youtu.be/a2MedFEQTeA">Ep 63</a>, I learned about both the <code>format()</code> function and the use of <code>knitr::knit_hooks$set(inline=SOME_FUNCTION)</code>. Using <code>format()</code> with <code>kinter</code> hooks is far superior to my prior repetitive and hacky approach to formatting inline values. <code>format()</code> strikes me as the correct way to present inline numbers because it does not change the value of the variable–which <code>round()</code> does. Whether done inline or using hooks, it is a simple matter to call <code>format()</code> rather than <code>round()</code>. Unfortunately, this does not solve the matter of reporting small <span class="math inline">\(p\)</span> values.</p>
<p>APA, like many other styles calls for special treatment of small <span class="math inline">\(p\)</span> values. APA style <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">instructs</a>, authors to “report exact p values (e.g., p = .015), unless p is &lt; .001 (instead write as”&lt;.001”).”</p>
<p>With either method, reporting very small <span class="math inline">\(p\)</span> values is tricky. In my experience, <code>round()</code> and <code>format()</code> do no deal very well with small <span class="math inline">\(p\)</span> values. Both functions return <code>0</code> which isn’t useful. That’s unfortunate because often times we are really interested in tests that return low <span class="math inline">\(p\)</span> values. Whether the threshold is “&lt;0.05” or “&lt;0.001”, converting the small <span class="math inline">\(p\)</span> value into the necessary text requires a custom conditional expression. Fortunately, there are some existing <a href="https://scriptsandstatistics.wordpress.com/2019/09/22/formating-p-values-a-curated-list-of-r-functions/">solutions</a>; below I illustrate my current favorite approach which relies on the <code>scales</code> package. <em>Let’s get into it.</em></p>
</section>
<section id="conditional-formatting-of-inline-code-using-knitrknit_hooks" class="level1">
<h1>Conditional formatting of inline code using <code>knitr::knit_hooks()</code></h1>
<p>The <code>knitr</code> library supports something called “<a href="https://yihui.org/knitr/hooks/">hooks</a>” which until recently I never really pierced my consciousness. Hooks are custom functions that run before or after a chunk and can be used for a range of purposes including formatting, altering chunk options, or adjusting output. In this case, a hook is used for creating a custom function to perform conditional formatting of numbers for inline reporting.</p>
<p>I borrowed the <code>inline_hook()</code> function below from <a href="https://www.schlosslab.org/">Dr.&nbsp;Schloss</a>. This custom function evaluates numbers to see if they are integers. If they are, the number is reported with no decimals and commas are used in the thousands place via <code>format(x, digits=0, big.mark = ",")</code>. If the number is floating point, the number is formatted two significant figures and commas are used in the thousands. In this case, if the number is a very small fraction, R reports out to as many significant figures as are necessary to represent the fraction. This is important to consider when reporting <span class="math inline">\(p\)</span> values.</p>
<div class="cell">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/d3vRj0cLI88" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p>Three parts of the inline hook function can be set up to bold the inline output; this can be useful for temporarily identifying inline results in the output for the purpose of checking that the values are formatted correctly. Both the interger and floating point sections can be set to bold. There is also the option to bold all characters called from inline code. Here bold is turned on for numbers; turn it off by commenting out the lines that read <code>formatted &lt;- paste0("**", formatted, "**")</code>. Generally, for a final product one would want it off. I’ve left bold on for numbers to help highlight text that is produced by inline code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create custom hook for knitr</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>inline_hook <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">is.numeric</span>(x)){</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(<span class="fu">abs</span>(x <span class="sc">-</span> <span class="fu">round</span>(x)) <span class="sc">&lt;</span> .Machine<span class="sc">$</span>double.eps){</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>      <span class="co"># treat as integer</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>      formatted <span class="ot">&lt;-</span> <span class="fu">format</span>(x, <span class="at">digits=</span><span class="dv">0</span>, <span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>      <span class="co"># comment out to turn off bold</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      formatted <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"**"</span>, formatted, <span class="st">"**"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>      } <span class="cf">else</span> {</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># treat as floating point number</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        formatted <span class="ot">&lt;-</span> <span class="fu">format</span>(x, <span class="at">digits=</span><span class="dv">2</span>, <span class="at">nsmall=</span><span class="dv">3</span>, <span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># comment out to turn off bold</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        formatted <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"**"</span>, formatted, <span class="st">"**"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      formatted <span class="ot">&lt;-</span>x</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># uncomment this line for bold</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># paste0("**", formatted, "**")</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># uncomment this line for unbolded</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  formatted</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># call custom formatting hook</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>knit_hooks<span class="sc">$</span><span class="fu">set</span>(<span class="at">inline=</span>inline_hook)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># set general options</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Turn off scientific notation</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">9999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
</section>
<section id="exploring-inline-formatting-of-numeric-variables" class="level1">
<h1>Exploring inline formatting of numeric variables</h1>
<p>It is useful to explore how inline code gets reported based on the conditional hooks implemented above. Below are some test numbers and a toy data frame that can be used to examine difference scenarios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>integer1 <span class="ot">&lt;-</span> <span class="dv">100000000</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>float1 <span class="ot">&lt;-</span> <span class="fl">0.123456789</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>float2 <span class="ot">&lt;-</span> <span class="fl">0.000000021</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>float3 <span class="ot">&lt;-</span> <span class="fl">123456789.987654321</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>float4 <span class="ot">&lt;-</span> <span class="fl">123456789.000000021</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">right =</span> <span class="fu">rbeta</span>(<span class="dv">1000</span>, <span class="dv">10</span>, <span class="dv">2</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">normal =</span><span class="fu">rnorm</span>(<span class="dv">1000</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">left =</span> <span class="fu">rbeta</span>(<span class="dv">1000</span>, <span class="dv">2</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Integer 1: <strong>100,000,000</strong> This works just fine and is not likely to present any problems. The <code>big.mark</code> argument of <code>format()</code> is used to set the comma. Scientific notation is turned off with <code>options(scipen = 9999)</code>, otherwise large numbers are reported using scientific notation.</li>
<li>Float 1: <strong>0.123</strong> This also works fine.</li>
<li>Float 2: <strong>0.000000021</strong> Since the value is so small, R reports out to many decimal places even with <code>format()</code> in place.</li>
<li>Float 2 rounded at two digits: <strong>0</strong> If we round this very small fraction, it rounds to zero. If we have small <span class="math inline">\(p\)</span> values in a statistical test, this will not do.</li>
<li>Float 2 using <code>scales</code> package: &lt;0.01 As <a href="https://scriptsandstatistics.wordpress.com/2019/09/22/formating-p-values-a-curated-list-of-r-functions/">suggested</a> by Norbert Köhler, the <a href="https://scales.r-lib.org/"><code>scales</code></a> library offers a nice solution. This is written as <code>`r scales::pvalue(float2, accuracy = 0.01)`</code>.</li>
<li>Float 3: <strong>123,456,789.988</strong></li>
<li>Float 4: <strong>123,456,789.000</strong> For a regular number, rounding is fine, but it would be nice to drop the 0’s. This could be done with <code>round()</code> on a case by case basis like: <strong>123,456,789</strong> which we would write as <code>`r round(float4, digits = 0)`</code>. Really the major issue is when one wants to report a very small <span class="math inline">\(p\)</span> number.</li>
</ul>
</section>
<section id="reporting-statistical-tests-inline" class="level1">
<h1>Reporting statistical tests inline</h1>
<p>Access to statistical tests that can be performed using literate coding in a reproducible environment is one of the strengths of R Markdown. Once the test is run, accessing and manipulating the results can be a little tricky. Let’s use the <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">Shapiro-Wilk</a> test to see if the distributions in <code>df</code> are normal. We’ll start by looking at the normal distribution because the <span class="math inline">\(p\)</span> values are simpler to report.</p>
<div class="cell" data-fig.caption="Toy data sets for evaluating inline reporting of $p$ values." data-preview="true">
<div class="cell-output-display">
<p><img src="index_files/figure-html/plots-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create variables for each test</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these are used to call the values inline</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sh_right <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df<span class="sc">$</span>right)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>sh_normal <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df<span class="sc">$</span>normal)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>sh_left <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df<span class="sc">$</span>left)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># call the variable to see it</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>sh_normal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  df$normal
W = 0.99773, p-value = 0.1871</code></pre>
</div>
</div>
<p>Great, R output the results, the low <span class="math inline">\(p\)</span> value means we won’t reject the null hypothesis. However, raw R output isn’t very a “elegant” presentation or efficient use of space for a narrative. It would be much nicer to report the values inline as part of the prose. Doing this requires knowing how to access the various parts of the variable assigned to the test, which in this case is <code>sh_normal</code>. Let’s get a description of the variable that reveals where the test results are stored. This information is also shown in the “Environment” tab of RStudio, but we’ll call it here using <code>str()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sh_normal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 4
 $ statistic: Named num 0.998
  ..- attr(*, "names")= chr "W"
 $ p.value  : num 0.187
 $ method   : chr "Shapiro-Wilk normality test"
 $ data.name: chr "df$normal"
 - attr(*, "class")= chr "htest"</code></pre>
</div>
</div>
<p><code>str()</code>, the string function, exposes the internal structure of an R object, in this case displaying the names and values of the various portions of the test. Appended to the variable name, the extract function (<code>$</code>) is used to pull the name of the test, the test statistic which is <span class="math inline">\(W\)</span>, and the associated <span class="math inline">\(p\)</span> value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sh_normal<span class="sc">$</span>method</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Shapiro-Wilk normality test"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sh_normal<span class="sc">$</span>statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      W 
0.99773 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sh_normal<span class="sc">$</span>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1871114</code></pre>
</div>
</div>
<p>This gives us everything we need to report our statistic:</p>
<blockquote class="blockquote">
<p>The Shapiro-Wilk normality test shows no significant difference from a random distribution (<span class="math inline">\(W\)</span>= <strong>0.998</strong> <span class="math inline">\(p\)</span>= <strong>0.187</strong>).</p>
</blockquote>
<p>Provided the <code>knitr</code> library is loaded, this is written out as (minus the “**” Markdown characters which are turned on to make inline output bold):</p>
<blockquote class="blockquote">
<p>The <code>`r sh_normal$method`</code> shows no significant difference from a random distribution ($W$= <code>`r sh_normal$statistic`</code> $p$= <code>`r sh_normal$p.value`</code>).</p>
</blockquote>
<p>The same basic approach can be used for reporting other statistical tests. Let’s turn now to the issue of reporting very small <span class="math inline">\(p\)</span> values.</p>
</section>
<section id="reporting-p-values" class="level1">
<h1>Reporting <span class="math inline">\(p\)</span> values</h1>
<p>It is useful to know when a distribution is not normal or a test is rejected because it can change the course of analysis. For example, if a distribution is normal one might proceed with a parametric test but use a nonparametric test if the data to not appear normally distributed. When making tests, <span class="math inline">\(p\)</span> values are important and small values in particular are interesting because, they mean an extreme outcome is unlikely under the null hypothesis. The smaller <span class="math inline">\(p\)</span> the stronger the case that one can reject the null hypothesis. Therefore, it is important to properly report small <span class="math inline">\(p\)</span> values. This where the <code>scales</code> library is handy.</p>
<p>The <code>scales</code> library is about “converting from data values to perceptual properties.” It is built primarily for use with <code>ggplot2</code> but there are some general functions, including <code>pvalue()</code> which is specifically for reporting <span class="math inline">\(p\)</span> values. The related <code>label_pvalue()</code> performs a similar task but works on <code>ggplot2</code> legends.</p>
<section id="right-skewed-distribution" class="level2">
<h2 class="anchored" data-anchor-id="right-skewed-distribution">Right skewed distribution</h2>
<ul>
<li><p>When the distribution is right skewed, reporting <span class="math inline">\(p\)</span> as a number does not work well (<span class="math inline">\(W\)</span>= <strong>0.940</strong> <span class="math inline">\(p\)</span>= <strong>0</strong>).</p></li>
<li><p>With p reported using <code>scales</code> it works very well (<span class="math inline">\(W\)</span>= <strong>0.940</strong> <span class="math inline">\(p\)</span>= &lt;0.01).</p>
<ul>
<li><p>Inline code: <span class="math inline">\(W\)</span> = <code>`r sh_right$statistic`</code></p></li>
<li><p>Inline code: <span class="math inline">\(p\)</span> = <code>`r pvalue(sh_right$p.value, accuracy = 0.01)`</code>. Note that here the expression is surrounded by <code>**</code> because inline code is set to format with bold in markdown.</p></li>
</ul></li>
</ul>
</section>
<section id="a-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="a-normal-distribution">A normal distribution</h2>
<ul>
<li>When the distribution is normal, reporting <span class="math inline">\(p\)</span> as a number works fine because it is by definition a larger fraction (<span class="math inline">\(W\)</span>= <strong>0.998</strong> <span class="math inline">\(p\)</span>= <strong>0.187</strong>).</li>
</ul>
</section>
<section id="left-skewed-distribution" class="level2">
<h2 class="anchored" data-anchor-id="left-skewed-distribution">Left skewed distribution</h2>
<ul>
<li><p>When the distribution is left skewed, reporting <span class="math inline">\(p\)</span> as a number does not work well (<span class="math inline">\(W\)</span>= <strong>0.939</strong> <span class="math inline">\(p\)</span>= <strong>0</strong>).</p></li>
<li><p>With p reported using <code>scales</code> it works very well (<span class="math inline">\(W\)</span>= <strong>0.939</strong> <span class="math inline">\(p\)</span>= &lt;0.01).</p>
<ul>
<li><p>Inline code: <span class="math inline">\(W\)</span> = <code>`r sh_right$statistic`</code></p></li>
<li><p>Inline code: <span class="math inline">\(p\)</span> = <code>`r pvalue(sh_right$p.value, accuracy = 0.01)`</code>. Note that here the expression is surrounded by <code>**</code> because inline code is set to format with bold in markdown.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="helpful-links" class="level1 unnumbered page-columns page-full">
<h1 class="unnumbered">Helpful Links:</h1>
<div class="cell page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<p><img src="https://i.imgur.com/ht1oaYc.jpeg" class="img-fluid"></p>
</div></div></div>
<ul>
<li><a href="https://www.youtube.com/watch?v=a2MedFEQTeA">Formatting the output of inline code in R Markdown documents to make it look natural (CC063) - YouTube</a></li>
<li><a href="https://scriptsandstatistics.wordpress.com/2019/09/22/formating-p-values-a-curated-list-of-r-functions/">Formatting p-values: A curated list of R functions – Scripts &amp; Statistics</a></li>
<li><a href="https://rviews.rstudio.com/2017/12/04/how-to-show-r-inline-code-blocks-in-r-markdown/">How to Show R Inline Code Blocks in R Markdown · R Views</a></li>
<li><a href="https://yihui.org/en/2017/11/knitr-verbatim-code-chunk/">Generate A Verbatim Code Chunk or Inline R Expression in knitr Output - Yihui Xie | 谢益辉</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>